#server.port=8080
#
#spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ecommerce_website}
#spring.datasource.username=root
##spring.datasource.password=debraj
#spring.datasource.password=${DB_PASSWORD}
#
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#spring.application.name=ecommerce-backend

server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:ecommerce_website}

spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:debraj}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.application.name=ecommerce-backend


razorpay.api.key = rzp_test_SoTEJCuxA1lnOz

razorpay.api.secret = iLoFYiaqPGIlu1ujpDklkvm7

#DB_HOST:mysql.railway.internal
#DB_PORT:3306
#DB_NAME:railway
#DB_PASSWORD:ckPczYyuzkaNXriHMGhqdFsGgkLPeMEU
#DB_USERNAME:root